# Generated by Django 5.1.4 on 2025-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Copper', 'Copper'), ('Bronze', 'Bronze'), ('Rainbow', 'Rainbow'), ('Transparent', 'Transparent'), ('Multi-Color', 'Multi-Color')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50),
        ),
    ]
