# Generated by Django 5.1.4 on 2025-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
